# .github/workflows/azure-deploy-backend.yml
name: Deploy MVMNT Backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies & run tests (backend only)
        working-directory: ./mvmnt-backend
        run: |
          npm install
          npm test --if-present

      - name: Zip backend for deployment
        working-directory: ./mvmnt-backend
        run: |
          zip -r ../backend-release.zip .  

      - name: Upload backend package
        uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: backend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-package
    steps:
      - name: Download backend package
        uses: actions/download-artifact@v4
        with:
          name: backend-package

      - name: Unzip package
        run: unzip backend-release.zip -d ./mvmnt-backend

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:     ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'muvs-backend-abc'
          slot-name: 'Production'
          package: './mvmnt-backend'
