name: Build & Deploy Backend to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install & Test (backend)
        working-directory: ./mvmnt-backend
        run: |
          npm install
          npm test --if-present

      - name: Zip backend for deployment
        run: |
          zip -r backend-release.zip mvmnt-backend

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: backend-release.zip

  deploy:
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: backend-package

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'muvs-backend-abc'
          slot-name: 'Production'
          package: 'backend-release.zip'
