name: Build & Deploy Backend to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install & Test (backend)
        working-directory: ./mvmnt-backend
        run: |
          npm install
          npm test --if-present

      - name: Package for Deployment
        working-directory: ./mvmnt-backend
        run: zip -r ../backend-release.zip .

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: backend-release.zip

  deploy:
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-package

      - name: Unzip Package
        run: unzip backend-release.zip -d ./mvmnt-backend

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'muvs-backend-abc'
          slot-name: 'Production'
          package: './mvmnt-backend'
